version: '3'
services:
  tango:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on:
      - redis

  redis:
    image: 'redis:latest'
