version: "3.8"
services:
  redis:
    image: redis:latest
    deploy:
      replicas: 1
  tango:
    container_name: tango
    ports:
      - '3000:3000'
    build: 
      context: ./Tango
    depends_on:
      - "redis"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Tango/config.template.py:/opt/TangoService/Tango/config.py
    environment:
      - DOCKER_DEPLOYMENT=true
  autolab:
    container_name: autolab
    ports:
      - '80:80'
      - '443:443'
    build: ./Autolab

    # Some volume mappings may seem redundant, but we want to make it explicit
    volumes:
      - ./Autolab/db/:/home/app/webapp/db
      - ./Autolab/config/database.yml:/home/app/webapp/config/database.yml
      - ./Autolab/config/initializers/devise.rb:/home/app/webapp/config/initializers/devise.rb
      - ./Autolab/config/environments/production.rb:/home/app/webapp/config/environments/production.rb
      - ./Autolab/config/autogradeConfig.rb:/home/app/webapp/config/autogradeConfig.rb
      - ./Autolab/courses:/home/app/webapp/courses
      - ./Autolab/docker/nginx.conf:/etc/nginx/sites-enabled/webapp.conf
    environment:
      - DOCKER_SSL=false
      - RESTFUL_HOST=tango
      - RESTFUL_PORT=3000
      - RESTFUL_KEY=REPLACE_ME_SECRET_TANGO_KEY
