version: '3'
services:
  tango:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app/tango
  redis:
    image: 'redis:latest'
